// ─── Format employee for API response ────────────────────────────────────────
const formatEmployee = (e) => {
  if (!e) return null;
  return {
    id: e.id,
    loginId: e.loginId,
    email: e.email,
    role: e.role?.toLowerCase(),
    firstName: e.firstName,
    lastName: e.lastName,
    avatar: e.avatar,
    jobPosition: e.jobPosition,
    department: e.department,
    managerId: e.managerId,
    location: e.location,
    phone: e.phone,
    companyId: e.companyId,
    companyName: e.company?.name,
    companyAbbr: e.company?.abbreviation,
    companyLogo: e.company?.logo,
    yearOfJoining: e.yearOfJoining,
    serialNumber: e.serialNumber,
    dateOfBirth: e.dateOfBirth,
    residingAddress: e.residingAddress,
    nationality: e.nationality,
    personalEmail: e.personalEmail,
    gender: e.gender,
    maritalStatus: e.maritalStatus,
    dateOfJoining: e.dateOfJoining,
    empCode: e.empCode,
    accountNumber: e.accountNumber,
    bankName: e.bankName,
    ifscCode: e.ifscCode,
    panNo: e.panNo,
    uanNo: e.uanNo,
    about: e.about,
    whatILove: e.whatILove,
    hobbies: e.hobbies,
    skills: e.skills || [],
    certifications: e.certifications || [],
    monthlyWage: parseFloat(e.monthlyWage) || 0,
    workingDaysPerWeek: e.workingDaysPerWeek,
    breakTimeHrs: parseFloat(e.breakTimeHrs) || 1,
    isActive: e.isActive,
    createdAt: e.createdAt,
  };
};

module.exports = { formatEmployee };
